packer_password     = "packer"
ansible_login       = "jubeaz"
ansible_password    = "jubeaz"
arch_add_pkgs       = ""
domain              = "local"
hostname            = "packer"
countries           = "Fance,Germany"
keymap              = "fr"
locale              = "fr_FR.UTF-8"
ufw_allow_ssh_ip    = "192.168.2.0/24"
ntp_pools           = "0.fr.pool.ntp.org, 1.fr.pool.ntp.org, 2.fr.pool.ntp.org, 3.fr.pool.ntp.org"
hostname            = "packer"

cpu                 = "2"
ram                 = "2048"
disk_size           = "90000"
headless            = "false"
shutdown_command    = "sudo shutdown now"